# Makefile for Python project

# Variables
PYTHON = python3
ARGS = 3 10 Basic_Green_Cards.txt Basic_RED_cards.txt

# Default target
all: run

# Run the main file
run:
	$(PYTHON) main.py $(ARGS)

# Clean the project
clean:
	rm -rf __pycache__